{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdcab674-6fae-451d-8317-f6335c91a6ad",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import annotations\n",
    "\n",
    "import random\n",
    "from typing import Dict, List, Tuple, Optional, Set\n",
    "\n",
    "\n",
    "TripMap = Dict[int, dict]\n",
    "TTBestMap = Dict[Tuple[int, int], Tuple[int, dict]]\n",
    "Chromosome = List[List[int]]\n",
    "\n",
    "\n",
    "def tt_energy_duration(\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    v: int,\n",
    ") -> Tuple[float, int]:\n",
    "    \"\"\"\n",
    "    Return deadhead energy and duration for connection i -> v.\n",
    "    \"\"\"\n",
    "\n",
    "    item = tt_best.get((i, v))\n",
    "\n",
    "    if item is None:\n",
    "        return float(\"inf\"), 10**12\n",
    "\n",
    "    _, deadhead = item\n",
    "\n",
    "    energy = float(deadhead.get(\"energy\", float(\"inf\")))\n",
    "    duration = int(deadhead.get(\"duration\", 10**12))\n",
    "\n",
    "    return energy, duration\n",
    "\n",
    "\n",
    "def is_time_feasible(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    v: int,\n",
    "    allow_equal: bool = True,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Check whether trip v can follow trip i.\n",
    "    \"\"\"\n",
    "\n",
    "    if i not in trips or v not in trips:\n",
    "        return False\n",
    "\n",
    "    energy, duration = tt_energy_duration(tt_best, i, v)\n",
    "\n",
    "    if energy == float(\"inf\"):\n",
    "        return False\n",
    "\n",
    "    arrival_time = int(trips[i][\"end\"]) + duration\n",
    "    start_v = int(trips[v][\"start\"])\n",
    "\n",
    "    if allow_equal:\n",
    "        return arrival_time <= start_v\n",
    "\n",
    "    return arrival_time < start_v\n",
    "\n",
    "\n",
    "def idle_time(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    v: int,\n",
    ") -> int:\n",
    "    \"\"\"\n",
    "    Return waiting time before trip v starts.\n",
    "    \"\"\"\n",
    "\n",
    "    _, duration = tt_energy_duration(tt_best, i, v)\n",
    "\n",
    "    arrival_time = int(trips[i][\"end\"]) + duration\n",
    "    start_v = int(trips[v][\"start\"])\n",
    "\n",
    "    return max(0, start_v - arrival_time)\n",
    "\n",
    "\n",
    "def score_successor(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    v: int,\n",
    "    alpha: float,\n",
    "    beta: float,\n",
    "    gamma: float,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Compute the initialization score:\n",
    "\n",
    "        s(i, v) = alpha * dur(i, v)\n",
    "                + beta  * energy(i, v)\n",
    "                + gamma * idle(i, v)\n",
    "\n",
    "    Duration and idle time are measured in minutes.\n",
    "    Energy is measured in Wh.\n",
    "    \"\"\"\n",
    "\n",
    "    energy, duration_seconds = tt_energy_duration(tt_best, i, v)\n",
    "    idle_seconds = idle_time(trips, tt_best, i, v)\n",
    "\n",
    "    duration_minutes = duration_seconds / 60.0\n",
    "    idle_minutes = idle_seconds / 60.0\n",
    "\n",
    "    return (\n",
    "        alpha * duration_minutes\n",
    "        + beta * energy\n",
    "        + gamma * idle_minutes\n",
    "    )\n",
    "\n",
    "\n",
    "def initialize_chromosome(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    alpha: float = 1.0,\n",
    "    beta: float = 1e-4,\n",
    "    gamma: float = 0.10,\n",
    "    epsilon: float = 0.10,\n",
    "    delta: float = 0.0,\n",
    "    allow_equal: bool = True,\n",
    "    rng: Optional[random.Random] = None,\n",
    ") -> Chromosome:\n",
    "    \"\"\"\n",
    "    Construct one initial chromosome using the thesis initialization procedure.\n",
    "\n",
    "    The heuristic repeatedly selects the earliest unassigned trip as a seed and\n",
    "    greedily appends feasible successors while maintaining time feasibility.\n",
    "\n",
    "    Each feasible successor v after current trip i is scored by:\n",
    "\n",
    "        s(i, v) = alpha * dur(i, v)\n",
    "                + beta  * energy(i, v)\n",
    "                + gamma * idle(i, v)\n",
    "\n",
    "    Independent jitter is added to the score, and epsilon-greedy selection is\n",
    "    used to balance exploitation and exploration.\n",
    "    \"\"\"\n",
    "\n",
    "    rng = rng or random.Random()\n",
    "\n",
    "    unassigned: Set[int] = set(trips.keys())\n",
    "\n",
    "    ordered_trips = sorted(\n",
    "        trips.keys(),\n",
    "        key=lambda t: (\n",
    "            int(trips[t][\"start\"]),\n",
    "            int(trips[t][\"end\"]),\n",
    "            t,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "    chromosome: Chromosome = []\n",
    "\n",
    "    while unassigned:\n",
    "        # Select a seed among the earliest unassigned trips.\n",
    "        seed = next(t for t in ordered_trips if t in unassigned)\n",
    "\n",
    "        chain = [seed]\n",
    "        unassigned.remove(seed)\n",
    "\n",
    "        current = seed\n",
    "\n",
    "        while True:\n",
    "            feasible_candidates = [\n",
    "                v\n",
    "                for v in unassigned\n",
    "                if is_time_feasible(\n",
    "                    trips=trips,\n",
    "                    tt_best=tt_best,\n",
    "                    i=current,\n",
    "                    v=v,\n",
    "                    allow_equal=allow_equal,\n",
    "                )\n",
    "            ]\n",
    "\n",
    "            if not feasible_candidates:\n",
    "                break\n",
    "\n",
    "            scored_candidates: List[Tuple[float, int]] = []\n",
    "\n",
    "            for v in feasible_candidates:\n",
    "                score = score_successor(\n",
    "                    trips=trips,\n",
    "                    tt_best=tt_best,\n",
    "                    i=current,\n",
    "                    v=v,\n",
    "                    alpha=alpha,\n",
    "                    beta=beta,\n",
    "                    gamma=gamma,\n",
    "                )\n",
    "\n",
    "                jitter = rng.uniform(-delta, delta) if delta > 0 else 0.0\n",
    "                perturbed_score = score + jitter\n",
    "\n",
    "                scored_candidates.append((perturbed_score, v))\n",
    "\n",
    "            u = rng.random()\n",
    "\n",
    "            if u < epsilon:\n",
    "                # Exploration\n",
    "                selected = rng.choice(feasible_candidates)\n",
    "            else:\n",
    "                # Exploitation\n",
    "                selected = min(scored_candidates, key=lambda item: item[0])[1]\n",
    "\n",
    "            chain.append(selected)\n",
    "            unassigned.remove(selected)\n",
    "            current = selected\n",
    "\n",
    "        chromosome.append(chain)\n",
    "\n",
    "    return chromosome\n",
    "\n",
    "\n",
    "def initialize_population(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    population_size: int,\n",
    "    alpha: float = 1.0,\n",
    "    beta: float = 1e-4,\n",
    "    gamma: float = 0.10,\n",
    "    epsilon: float = 0.10,\n",
    "    delta: float = 0.0,\n",
    "    allow_equal: bool = True,\n",
    "    seed: Optional[int] = None,\n",
    ") -> List[Chromosome]:\n",
    "    \"\"\"\n",
    "    Generate the initial population by repeatedly applying the constructive\n",
    "    initialization heuristic with randomized jitter and epsilon-greedy choices.\n",
    "    \"\"\"\n",
    "\n",
    "    rng = random.Random(seed)\n",
    "\n",
    "    return [\n",
    "        initialize_chromosome(\n",
    "            trips=trips,\n",
    "            tt_best=tt_best,\n",
    "            alpha=alpha,\n",
    "            beta=beta,\n",
    "            gamma=gamma,\n",
    "            epsilon=epsilon,\n",
    "            delta=delta,\n",
    "            allow_equal=allow_equal,\n",
    "            rng=rng,\n",
    "        )\n",
    "        for _ in range(population_size)\n",
    "    ]\n",
    "# Optional backward-compatible name.\n",
    "smart_chromosome_A = initialize_chromosome"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
