{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8cf88939-490e-40a0-95d8-bcd9a904a934",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import annotations\n",
    "\n",
    "import random\n",
    "from typing import List, Optional, Sequence, Tuple\n",
    "\n",
    "\n",
    "Chromosome = List[List[int]]\n",
    "ScoredIndividual = Tuple[float, object]\n",
    "\n",
    "\n",
    "def copy_chromosome(chromosome: Chromosome) -> Chromosome:\n",
    "    \"\"\"\n",
    "    Return a deep copy of a chromosome.\n",
    "    \"\"\"\n",
    "\n",
    "    return [list(chain) for chain in chromosome]\n",
    "\n",
    "\n",
    "def tournament_selection(\n",
    "    population: Sequence[Chromosome],\n",
    "    scored: Sequence[ScoredIndividual],\n",
    "    tournament_k: int,\n",
    "    rng: Optional[random.Random] = None,\n",
    ") -> Chromosome:\n",
    "    \"\"\"\n",
    "    Select one parent using tournament selection.\n",
    "\n",
    "    A subset of individuals is sampled uniformly at random from the population.\n",
    "    The individual with the lowest fitness value wins the tournament.\n",
    "    \"\"\"\n",
    "\n",
    "    if not population:\n",
    "        raise ValueError(\"population must not be empty.\")\n",
    "\n",
    "    if len(population) != len(scored):\n",
    "        raise ValueError(\"population and scored must have the same length.\")\n",
    "\n",
    "    rng = rng or random.Random()\n",
    "\n",
    "    candidate_indices = rng.sample(\n",
    "        range(len(population)),\n",
    "        k=min(tournament_k, len(population)),\n",
    "    )\n",
    "\n",
    "    best_index = min(\n",
    "        candidate_indices,\n",
    "        key=lambda i: scored[i][0],\n",
    "    )\n",
    "\n",
    "    return copy_chromosome(population[best_index])\n",
    "\n",
    "\n",
    "def sort_population_by_fitness(\n",
    "    population: Sequence[Chromosome],\n",
    "    scored: Sequence[ScoredIndividual],\n",
    ") -> Tuple[List[Chromosome], List[ScoredIndividual]]:\n",
    "    \"\"\"\n",
    "    Sort population and scores by fitness.\n",
    "\n",
    "    Lower fitness is better.\n",
    "    \"\"\"\n",
    "\n",
    "    if len(population) != len(scored):\n",
    "        raise ValueError(\"population and scored must have the same length.\")\n",
    "\n",
    "    order = sorted(\n",
    "        range(len(population)),\n",
    "        key=lambda i: scored[i][0],\n",
    "    )\n",
    "\n",
    "    sorted_population = [copy_chromosome(population[i]) for i in order]\n",
    "    sorted_scored = [scored[i] for i in order]\n",
    "\n",
    "    return sorted_population, sorted_scored\n",
    "\n",
    "\n",
    "def select_elites(\n",
    "    population: Sequence[Chromosome],\n",
    "    scored: Sequence[ScoredIndividual],\n",
    "    elite_k: int,\n",
    ") -> List[Chromosome]:\n",
    "    \"\"\"\n",
    "    Copy the best chromosomes unchanged into the next generation.\n",
    "\n",
    "    This implements elitism.\n",
    "    \"\"\"\n",
    "\n",
    "    if elite_k <= 0:\n",
    "        return []\n",
    "\n",
    "    sorted_population, _ = sort_population_by_fitness(population, scored)\n",
    "\n",
    "    return [\n",
    "        copy_chromosome(chromosome)\n",
    "        for chromosome in sorted_population[:elite_k]\n",
    "    ]"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
