{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ce1d0e11-8329-4524-810b-18d762594609",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import annotations\n",
    "\n",
    "import random\n",
    "from typing import Dict, List, Optional, Sequence, Tuple\n",
    "\n",
    "\n",
    "TripMap = Dict[int, dict]\n",
    "TTBestMap = Dict[Tuple[int, int], Tuple[int, dict]]\n",
    "DTBestMap = Dict[int, Tuple[int, int, dict]]\n",
    "TDBestMap = Dict[int, Tuple[int, int, dict]]\n",
    "\n",
    "Chromosome = List[List[int]]\n",
    "\n",
    "INF = 10**18\n",
    "\n",
    "\n",
    "def copy_chromosome(chromosome: Chromosome) -> Chromosome:\n",
    "    \"\"\"\n",
    "    Return a deep copy of a chromosome.\n",
    "    \"\"\"\n",
    "\n",
    "    return [list(chain) for chain in chromosome]\n",
    "\n",
    "\n",
    "def tt_duration(\n",
    "    tt_best: TTBestMap,\n",
    "    u: int,\n",
    "    v: int,\n",
    ") -> int:\n",
    "    \"\"\"\n",
    "    Return trip-to-trip deadhead duration for edge u -> v.\n",
    "    \"\"\"\n",
    "\n",
    "    item = tt_best.get((u, v))\n",
    "\n",
    "    if item is None:\n",
    "        return INF\n",
    "\n",
    "    _, deadhead = item\n",
    "    return int(deadhead.get(\"duration\", INF))\n",
    "\n",
    "\n",
    "def tt_length(\n",
    "    tt_best: TTBestMap,\n",
    "    u: int,\n",
    "    v: int,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Return trip-to-trip deadhead distance for edge u -> v.\n",
    "    \"\"\"\n",
    "\n",
    "    item = tt_best.get((u, v))\n",
    "\n",
    "    if item is None:\n",
    "        return float(\"inf\")\n",
    "\n",
    "    _, deadhead = item\n",
    "    return float(deadhead.get(\"length\", float(\"inf\")))\n",
    "\n",
    "\n",
    "def dt_length(\n",
    "    dt_best: DTBestMap,\n",
    "    v: int,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Return depot-to-trip deadhead distance for edge depot -> v.\n",
    "    \"\"\"\n",
    "\n",
    "    item = dt_best.get(v)\n",
    "\n",
    "    if item is None:\n",
    "        return float(\"inf\")\n",
    "\n",
    "    _, _, deadhead = item\n",
    "    return float(deadhead.get(\"length\", float(\"inf\")))\n",
    "\n",
    "\n",
    "def td_length(\n",
    "    td_best: TDBestMap,\n",
    "    u: int,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Return trip-to-depot deadhead distance for edge u -> depot.\n",
    "    \"\"\"\n",
    "\n",
    "    item = td_best.get(u)\n",
    "\n",
    "    if item is None:\n",
    "        return float(\"inf\")\n",
    "\n",
    "    _, _, deadhead = item\n",
    "    return float(deadhead.get(\"length\", float(\"inf\")))\n",
    "\n",
    "\n",
    "def edge_length(\n",
    "    left: Optional[int],\n",
    "    right: Optional[int],\n",
    "    tt_best: TTBestMap,\n",
    "    dt_best: DTBestMap,\n",
    "    td_best: TDBestMap,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Return the deadhead distance of an edge.\n",
    "\n",
    "    Cases:\n",
    "        left is None, right is trip:\n",
    "            depot -> right\n",
    "\n",
    "        left is trip, right is None:\n",
    "            left -> depot\n",
    "\n",
    "        left is trip, right is trip:\n",
    "            left -> right\n",
    "\n",
    "        left is None, right is None:\n",
    "            empty chain case\n",
    "    \"\"\"\n",
    "\n",
    "    if left is None and right is None:\n",
    "        return 0.0\n",
    "\n",
    "    if left is None:\n",
    "        return dt_length(dt_best, right)\n",
    "\n",
    "    if right is None:\n",
    "        return td_length(td_best, left)\n",
    "\n",
    "    return tt_length(tt_best, left, right)\n",
    "\n",
    "\n",
    "def is_time_feasible_pair(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    u: int,\n",
    "    v: int,\n",
    "    allow_equal: bool = True,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Check whether trip v can follow trip u in time.\n",
    "    \"\"\"\n",
    "\n",
    "    if u not in trips or v not in trips:\n",
    "        return False\n",
    "\n",
    "    duration = tt_duration(tt_best, u, v)\n",
    "\n",
    "    if duration >= INF:\n",
    "        return False\n",
    "\n",
    "    arrival_time = int(trips[u][\"end\"]) + duration\n",
    "    start_v = int(trips[v][\"start\"])\n",
    "\n",
    "    if allow_equal:\n",
    "        return arrival_time <= start_v\n",
    "\n",
    "    return arrival_time < start_v\n",
    "\n",
    "\n",
    "def is_insertion_time_feasible(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    chain: Sequence[int],\n",
    "    position: int,\n",
    "    trip_id: int,\n",
    "    allow_equal: bool = True,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Check whether trip_id can be inserted into a chain at the given position.\n",
    "\n",
    "    position = 0:\n",
    "        insert before the first trip\n",
    "\n",
    "    position = len(chain):\n",
    "        insert after the last trip\n",
    "\n",
    "    position between 0 and len(chain):\n",
    "        insert between two trips\n",
    "    \"\"\"\n",
    "\n",
    "    left = chain[position - 1] if position > 0 else None\n",
    "    right = chain[position] if position < len(chain) else None\n",
    "\n",
    "    if left is not None:\n",
    "        if not is_time_feasible_pair(\n",
    "            trips=trips,\n",
    "            tt_best=tt_best,\n",
    "            u=left,\n",
    "            v=trip_id,\n",
    "            allow_equal=allow_equal,\n",
    "        ):\n",
    "            return False\n",
    "\n",
    "    if right is not None:\n",
    "        if not is_time_feasible_pair(\n",
    "            trips=trips,\n",
    "            tt_best=tt_best,\n",
    "            u=trip_id,\n",
    "            v=right,\n",
    "            allow_equal=allow_equal,\n",
    "        ):\n",
    "            return False\n",
    "\n",
    "    return True\n",
    "\n",
    "\n",
    "def removal_delta_length(\n",
    "    chain: Sequence[int],\n",
    "    position: int,\n",
    "    tt_best: TTBestMap,\n",
    "    dt_best: DTBestMap,\n",
    "    td_best: TDBestMap,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Compute ΔLrem for removing x from its original chain.\n",
    "\n",
    "    If x is removed from between two consecutive elements (a, x, b),\n",
    "    then edges (a, x) and (x, b) are replaced by (a, b):\n",
    "\n",
    "        ΔLrem = L(a, b) - L(a, x) - L(x, b)\n",
    "\n",
    "    This function also handles depot analogues:\n",
    "\n",
    "        x at beginning:\n",
    "            depot -> x -> b becomes depot -> b\n",
    "\n",
    "        x at end:\n",
    "            a -> x -> depot becomes a -> depot\n",
    "\n",
    "        x alone:\n",
    "            depot -> x -> depot becomes empty chain\n",
    "    \"\"\"\n",
    "\n",
    "    x = chain[position]\n",
    "\n",
    "    left = chain[position - 1] if position > 0 else None\n",
    "    right = chain[position + 1] if position + 1 < len(chain) else None\n",
    "\n",
    "    old_length = (\n",
    "        edge_length(left, x, tt_best, dt_best, td_best)\n",
    "        + edge_length(x, right, tt_best, dt_best, td_best)\n",
    "    )\n",
    "\n",
    "    new_length = edge_length(left, right, tt_best, dt_best, td_best)\n",
    "\n",
    "    return new_length - old_length\n",
    "\n",
    "\n",
    "def insertion_delta_length(\n",
    "    chain: Sequence[int],\n",
    "    position: int,\n",
    "    trip_id: int,\n",
    "    tt_best: TTBestMap,\n",
    "    dt_best: DTBestMap,\n",
    "    td_best: TDBestMap,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Compute ΔLins for inserting x into a target chain.\n",
    "\n",
    "    If x is inserted between two consecutive elements (u, v),\n",
    "    then edge (u, v) is replaced by (u, x) and (x, v):\n",
    "\n",
    "        ΔLins = L(u, x) + L(x, v) - L(u, v)\n",
    "\n",
    "    This function also handles depot analogues:\n",
    "\n",
    "        insert at beginning:\n",
    "            depot -> v becomes depot -> x -> v\n",
    "\n",
    "        insert at end:\n",
    "            u -> depot becomes u -> x -> depot\n",
    "\n",
    "        insert into empty chain:\n",
    "            empty chain becomes depot -> x -> depot\n",
    "    \"\"\"\n",
    "\n",
    "    left = chain[position - 1] if position > 0 else None\n",
    "    right = chain[position] if position < len(chain) else None\n",
    "\n",
    "    old_length = edge_length(left, right, tt_best, dt_best, td_best)\n",
    "\n",
    "    new_length = (\n",
    "        edge_length(left, trip_id, tt_best, dt_best, td_best)\n",
    "        + edge_length(trip_id, right, tt_best, dt_best, td_best)\n",
    "    )\n",
    "\n",
    "    return new_length - old_length\n",
    "\n",
    "\n",
    "def remove_empty_chains(chromosome: Chromosome) -> Chromosome:\n",
    "    \"\"\"\n",
    "    Remove empty chains from a chromosome.\n",
    "    \"\"\"\n",
    "\n",
    "    return [chain for chain in chromosome if chain]\n",
    "\n",
    "\n",
    "def best_relocate_mutation(\n",
    "    chromosome: Chromosome,\n",
    "    trips: TripMap,\n",
    "    dt_best: DTBestMap,\n",
    "    tt_best: TTBestMap,\n",
    "    td_best: TDBestMap,\n",
    "    allow_equal: bool = True,\n",
    "    seed: Optional[int] = None,\n",
    ") -> Chromosome:\n",
    "    \"\"\"\n",
    "    Best-relocate mutation.\n",
    "\n",
    "    This operator matches the thesis description.\n",
    "\n",
    "    A trip x is selected and removed from its original chain. Then all possible\n",
    "    time-feasible reinsertion positions are evaluated.\n",
    "\n",
    "    For removing x from its original chain:\n",
    "\n",
    "        ΔLrem = L(a, b) - L(a, x) - L(x, b)\n",
    "\n",
    "    For inserting x into a target chain:\n",
    "\n",
    "        ΔLins = L(u, x) + L(x, v) - L(u, v)\n",
    "\n",
    "    The total change in proxy deadhead distance is:\n",
    "\n",
    "        ΔL = ΔLins + ΔLrem\n",
    "\n",
    "    The best reinsertion position is the feasible position with the smallest ΔL.\n",
    "    The relocation is accepted only if this minimum ΔL is strictly negative.\n",
    "    Otherwise, the chromosome is returned unchanged.\n",
    "    \"\"\"\n",
    "\n",
    "    rng = random.Random(seed)\n",
    "    original = copy_chromosome(chromosome)\n",
    "    child = copy_chromosome(chromosome)\n",
    "\n",
    "    trip_positions: List[Tuple[int, int]] = [\n",
    "        (chain_index, position)\n",
    "        for chain_index, chain in enumerate(child)\n",
    "        for position in range(len(chain))\n",
    "    ]\n",
    "\n",
    "    if not trip_positions:\n",
    "        return child\n",
    "\n",
    "    source_chain_index, source_position = rng.choice(trip_positions)\n",
    "\n",
    "    source_chain = child[source_chain_index]\n",
    "    trip_id = source_chain[source_position]\n",
    "\n",
    "    delta_remove = removal_delta_length(\n",
    "        chain=source_chain,\n",
    "        position=source_position,\n",
    "        tt_best=tt_best,\n",
    "        dt_best=dt_best,\n",
    "        td_best=td_best,\n",
    "    )\n",
    "\n",
    "    # Remove x from its original position.\n",
    "    source_chain.pop(source_position)\n",
    "\n",
    "    # Remove empty source chain if x was the only trip in the chain.\n",
    "    if not source_chain:\n",
    "        child.pop(source_chain_index)\n",
    "\n",
    "    best_delta: Optional[float] = None\n",
    "    best_chain_index: Optional[int] = None\n",
    "    best_position: Optional[int] = None\n",
    "\n",
    "    # Test all feasible reinsertion positions in all existing chains.\n",
    "    for target_chain_index, target_chain in enumerate(child):\n",
    "        for insertion_position in range(len(target_chain) + 1):\n",
    "            if not is_insertion_time_feasible(\n",
    "                trips=trips,\n",
    "                tt_best=tt_best,\n",
    "                chain=target_chain,\n",
    "                position=insertion_position,\n",
    "                trip_id=trip_id,\n",
    "                allow_equal=allow_equal,\n",
    "            ):\n",
    "                continue\n",
    "\n",
    "            delta_insert = insertion_delta_length(\n",
    "                chain=target_chain,\n",
    "                position=insertion_position,\n",
    "                trip_id=trip_id,\n",
    "                tt_best=tt_best,\n",
    "                dt_best=dt_best,\n",
    "                td_best=td_best,\n",
    "            )\n",
    "\n",
    "            total_delta = delta_remove + delta_insert\n",
    "\n",
    "            if best_delta is None or total_delta < best_delta:\n",
    "                best_delta = total_delta\n",
    "                best_chain_index = target_chain_index\n",
    "                best_position = insertion_position\n",
    "\n",
    "    # Also test inserting x as a new singleton chain.\n",
    "    empty_chain: List[int] = []\n",
    "\n",
    "    delta_insert_singleton = insertion_delta_length(\n",
    "        chain=empty_chain,\n",
    "        position=0,\n",
    "        trip_id=trip_id,\n",
    "        tt_best=tt_best,\n",
    "        dt_best=dt_best,\n",
    "        td_best=td_best,\n",
    "    )\n",
    "\n",
    "    total_delta_singleton = delta_remove + delta_insert_singleton\n",
    "\n",
    "    if best_delta is None or total_delta_singleton < best_delta:\n",
    "        best_delta = total_delta_singleton\n",
    "        best_chain_index = len(child)\n",
    "        best_position = 0\n",
    "\n",
    "    # Accept the relocation only if it improves the proxy distance.\n",
    "    if (\n",
    "        best_delta is not None\n",
    "        and best_chain_index is not None\n",
    "        and best_position is not None\n",
    "        and best_delta < 0.0\n",
    "    ):\n",
    "        if best_chain_index == len(child):\n",
    "            child.append([trip_id])\n",
    "        else:\n",
    "            child[best_chain_index].insert(best_position, trip_id)\n",
    "\n",
    "        return remove_empty_chains(child)\n",
    "\n",
    "    # No improving relocation exists.\n",
    "    return original\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
