{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "75bbf663-dd62-49cc-b6d2-24f57c00758f",
   "metadata": {},
   "outputs": [],
   "source": [
    "from __future__ import annotations\n",
    "\n",
    "import random\n",
    "from typing import Dict, List, Optional, Sequence, Set, Tuple\n",
    "\n",
    "\n",
    "TripMap = Dict[int, dict]\n",
    "TTBestMap = Dict[Tuple[int, int], Tuple[int, dict]]\n",
    "Chromosome = List[List[int]]\n",
    "\n",
    "\n",
    "def copy_chromosome(chromosome: Chromosome) -> Chromosome:\n",
    "    \"\"\"Return a deep copy of a chromosome.\"\"\"\n",
    "\n",
    "    return [list(chain) for chain in chromosome]\n",
    "\n",
    "\n",
    "def tt_duration_length(\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    j: int,\n",
    ") -> Tuple[int, float]:\n",
    "    \"\"\"\n",
    "    Return deadhead duration and distance for connection i -> j.\n",
    "    \"\"\"\n",
    "\n",
    "    item = tt_best.get((i, j))\n",
    "\n",
    "    if item is None:\n",
    "        return 10**12, 1e18\n",
    "\n",
    "    _, deadhead = item\n",
    "\n",
    "    duration = int(deadhead.get(\"duration\", 10**12))\n",
    "    length = float(deadhead.get(\"length\", 1e18))\n",
    "\n",
    "    return duration, length\n",
    "\n",
    "\n",
    "def is_time_feasible(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    j: int,\n",
    "    allow_equal: bool = True,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Check whether trip j can follow trip i.\n",
    "    \"\"\"\n",
    "\n",
    "    if i not in trips or j not in trips:\n",
    "        return False\n",
    "\n",
    "    duration, _ = tt_duration_length(tt_best, i, j)\n",
    "\n",
    "    if duration >= 10**12:\n",
    "        return False\n",
    "\n",
    "    arrival_time = int(trips[i][\"end\"]) + duration\n",
    "    start_j = int(trips[j][\"start\"])\n",
    "\n",
    "    if allow_equal:\n",
    "        return arrival_time <= start_j\n",
    "\n",
    "    return arrival_time < start_j\n",
    "\n",
    "\n",
    "def edge_waiting_time(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    j: int,\n",
    ") -> int:\n",
    "    \"\"\"\n",
    "    Compute waiting time W(i,j).\n",
    "\n",
    "    W(i,j) = max(0, start(j) - (end(i) + tau(i,j)))\n",
    "    \"\"\"\n",
    "\n",
    "    duration, _ = tt_duration_length(tt_best, i, j)\n",
    "\n",
    "    arrival_time = int(trips[i][\"end\"]) + duration\n",
    "    start_j = int(trips[j][\"start\"])\n",
    "\n",
    "    return max(0, start_j - arrival_time)\n",
    "\n",
    "\n",
    "def edge_cost(\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    i: int,\n",
    "    j: int,\n",
    "    beta_wait: float = 0.005,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Compute crossover edge cost:\n",
    "\n",
    "        c(i,j) = L(i,j) + beta_wait * W(i,j)\n",
    "\n",
    "    where:\n",
    "        L(i,j) is deadhead distance,\n",
    "        W(i,j) is waiting time.\n",
    "    \"\"\"\n",
    "\n",
    "    _, length = tt_duration_length(tt_best, i, j)\n",
    "    wait = edge_waiting_time(trips, tt_best, i, j)\n",
    "\n",
    "    return length + beta_wait * wait\n",
    "\n",
    "\n",
    "def extract_parent_edges(\n",
    "    chromosome: Chromosome,\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    allow_equal: bool = True,\n",
    ") -> List[Tuple[int, int]]:\n",
    "    \"\"\"\n",
    "    Extract all consecutive trip pairs from a parent chromosome.\n",
    "    \"\"\"\n",
    "\n",
    "    edges: List[Tuple[int, int]] = []\n",
    "\n",
    "    for chain in chromosome:\n",
    "        for i, j in zip(chain, chain[1:]):\n",
    "            i = int(i)\n",
    "            j = int(j)\n",
    "\n",
    "            if is_time_feasible(trips, tt_best, i, j, allow_equal):\n",
    "                edges.append((i, j))\n",
    "\n",
    "    return edges\n",
    "\n",
    "\n",
    "def would_create_cycle(\n",
    "    successor: Dict[int, int],\n",
    "    i: int,\n",
    "    j: int,\n",
    ") -> bool:\n",
    "    \"\"\"\n",
    "    Check whether adding edge i -> j would create a cycle.\n",
    "    \"\"\"\n",
    "\n",
    "    current = j\n",
    "\n",
    "    while current in successor:\n",
    "        current = successor[current]\n",
    "\n",
    "        if current == i:\n",
    "            return True\n",
    "\n",
    "    return False\n",
    "\n",
    "\n",
    "def build_chains_from_successors(\n",
    "    all_trip_ids: Sequence[int],\n",
    "    successor: Dict[int, int],\n",
    "    predecessor: Dict[int, int],\n",
    "    trips: TripMap,\n",
    ") -> Chromosome:\n",
    "    \"\"\"\n",
    "    Convert successor/predecessor dictionaries into trip chains.\n",
    "    \"\"\"\n",
    "\n",
    "    used: Set[int] = set()\n",
    "    chromosome: Chromosome = []\n",
    "\n",
    "    ordered_trips = sorted(\n",
    "        [int(t) for t in all_trip_ids],\n",
    "        key=lambda t: (\n",
    "            int(trips[t][\"start\"]),\n",
    "            int(trips[t][\"end\"]),\n",
    "            t,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "    for trip_id in ordered_trips:\n",
    "        if trip_id in used:\n",
    "            continue\n",
    "\n",
    "        if trip_id in predecessor:\n",
    "            continue\n",
    "\n",
    "        chain: List[int] = []\n",
    "        current = trip_id\n",
    "\n",
    "        while current not in used:\n",
    "            chain.append(current)\n",
    "            used.add(current)\n",
    "\n",
    "            if current not in successor:\n",
    "                break\n",
    "\n",
    "            current = successor[current]\n",
    "\n",
    "        if chain:\n",
    "            chromosome.append(chain)\n",
    "\n",
    "    # Add any missing trips as singleton chains.\n",
    "    for trip_id in ordered_trips:\n",
    "        if trip_id not in used:\n",
    "            chromosome.append([trip_id])\n",
    "            used.add(trip_id)\n",
    "\n",
    "    return chromosome\n",
    "\n",
    "\n",
    "def insert_remaining_trips(\n",
    "    chromosome: Chromosome,\n",
    "    all_trip_ids: Sequence[int],\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    beta_wait: float = 0.005,\n",
    "    allow_equal: bool = True,\n",
    ") -> Chromosome:\n",
    "    \"\"\"\n",
    "    Insert trips that were not inherited through parent edges.\n",
    "\n",
    "    Each remaining trip is appended to the feasible chain that gives the lowest\n",
    "    edge cost. If no feasible insertion exists, a new singleton chain is created.\n",
    "    \"\"\"\n",
    "\n",
    "    used = {trip for chain in chromosome for trip in chain}\n",
    "\n",
    "    remaining = sorted(\n",
    "        [int(t) for t in all_trip_ids if int(t) not in used],\n",
    "        key=lambda t: (\n",
    "            int(trips[t][\"start\"]),\n",
    "            int(trips[t][\"end\"]),\n",
    "            t,\n",
    "        ),\n",
    "    )\n",
    "\n",
    "    for trip_id in remaining:\n",
    "        best_chain_index: Optional[int] = None\n",
    "        best_score: Optional[float] = None\n",
    "\n",
    "        for chain_index, chain in enumerate(chromosome):\n",
    "            tail = chain[-1]\n",
    "\n",
    "            if not is_time_feasible(trips, tt_best, tail, trip_id, allow_equal):\n",
    "                continue\n",
    "\n",
    "            score = edge_cost(\n",
    "                trips=trips,\n",
    "                tt_best=tt_best,\n",
    "                i=tail,\n",
    "                j=trip_id,\n",
    "                beta_wait=beta_wait,\n",
    "            )\n",
    "\n",
    "            if best_score is None or score < best_score:\n",
    "                best_score = score\n",
    "                best_chain_index = chain_index\n",
    "\n",
    "        if best_chain_index is None:\n",
    "            chromosome.append([trip_id])\n",
    "        else:\n",
    "            chromosome[best_chain_index].append(trip_id)\n",
    "\n",
    "    chromosome.sort(\n",
    "        key=lambda chain: (\n",
    "            int(trips[chain[0]][\"start\"]),\n",
    "            int(trips[chain[0]][\"end\"]),\n",
    "            chain[0],\n",
    "        )\n",
    "    )\n",
    "\n",
    "    return chromosome\n",
    "\n",
    "\n",
    "def edge_preserving_crossover(\n",
    "    parent1: Chromosome,\n",
    "    parent2: Chromosome,\n",
    "    all_trip_ids: Sequence[int],\n",
    "    trips: TripMap,\n",
    "    tt_best: TTBestMap,\n",
    "    beta_wait: float = 0.005,\n",
    "    allow_equal: bool = True,\n",
    "    seed: Optional[int] = None,\n",
    ") -> Chromosome:\n",
    "    \"\"\"\n",
    "    Edge-preserving crossover for time-feasible trip-chain chromosomes.\n",
    "\n",
    "    The operator follows the thesis description:\n",
    "\n",
    "    1. Extract consecutive trip pairs from both parents.\n",
    "    2. Score each edge by:\n",
    "\n",
    "           c(i,j) = L(i,j) + beta_wait * W(i,j)\n",
    "\n",
    "       where L is deadhead distance and W is waiting time.\n",
    "\n",
    "    3. Sort candidate edges by increasing cost.\n",
    "    4. Add edges to the child if:\n",
    "       - the tail has no successor yet,\n",
    "       - the head has no predecessor yet,\n",
    "       - the edge is time-feasible,\n",
    "       - adding the edge does not create a cycle.\n",
    "\n",
    "    5. Convert the selected edges into chains.\n",
    "    6. Insert trips not covered by inherited edges.\n",
    "    \"\"\"\n",
    "\n",
    "    rng = random.Random(seed)\n",
    "\n",
    "    edges_parent1 = extract_parent_edges(parent1, trips, tt_best, allow_equal)\n",
    "    edges_parent2 = extract_parent_edges(parent2, trips, tt_best, allow_equal)\n",
    "\n",
    "    candidate_edges = list(set(edges_parent1) | set(edges_parent2))\n",
    "\n",
    "    rng.shuffle(candidate_edges)\n",
    "\n",
    "    candidate_edges.sort(\n",
    "        key=lambda edge: edge_cost(\n",
    "            trips=trips,\n",
    "            tt_best=tt_best,\n",
    "            i=edge[0],\n",
    "            j=edge[1],\n",
    "            beta_wait=beta_wait,\n",
    "        )\n",
    "    )\n",
    "\n",
    "    successor: Dict[int, int] = {}\n",
    "    predecessor: Dict[int, int] = {}\n",
    "\n",
    "    for i, j in candidate_edges:\n",
    "        if i in successor:\n",
    "            continue\n",
    "\n",
    "        if j in predecessor:\n",
    "            continue\n",
    "\n",
    "        if not is_time_feasible(trips, tt_best, i, j, allow_equal):\n",
    "            continue\n",
    "\n",
    "        if would_create_cycle(successor, i, j):\n",
    "            continue\n",
    "\n",
    "        successor[i] = j\n",
    "        predecessor[j] = i\n",
    "\n",
    "    child = build_chains_from_successors(\n",
    "        all_trip_ids=all_trip_ids,\n",
    "        successor=successor,\n",
    "        predecessor=predecessor,\n",
    "        trips=trips,\n",
    "    )\n",
    "\n",
    "    child = insert_remaining_trips(\n",
    "        chromosome=child,\n",
    "        all_trip_ids=all_trip_ids,\n",
    "        trips=trips,\n",
    "        tt_best=tt_best,\n",
    "        beta_wait=beta_wait,\n",
    "        allow_equal=allow_equal,\n",
    "    )\n",
    "\n",
    "    return child\n",
    "\n",
    "\n",
    "# Backward-compatible name for your old code.\n",
    "crossover_preserve_edges_v2 = edge_preserving_crossover"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
