{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "01f9d7b5-074f-48c0-85f7-abbca5fac968",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import List, Optional\n",
    "import random\n",
    "import math\n",
    "\n",
    "\n",
    "def lns_ruin_recreate_v2(\n",
    "    chrom: List[List[int]],\n",
    "    trips,\n",
    "    dt_best,\n",
    "    tt_best,\n",
    "    ruin_frac: float = 0.20,\n",
    "    seed: Optional[int] = None,\n",
    "    allow_equal: bool = True\n",
    ") -> List[List[int]]:\n",
    "    \"\"\"\n",
    "    LNS ruin-and-recreate operator.\n",
    "\n",
    "    Ruin phase:\n",
    "        A fraction ruin_frac of service trips is randomly selected and removed\n",
    "        from all chains of the current offspring.\n",
    "\n",
    "    Recreate phase:\n",
    "        Removed trips are reinserted one by one. For each removed trip, all\n",
    "        time-feasible insertion positions across the current chains are checked.\n",
    "        The trip is inserted at the position that minimises the incremental\n",
    "        deadhead travel-time cost.\n",
    "    \"\"\"\n",
    "\n",
    "    rng = random.Random(seed)\n",
    "\n",
    "    # Copy chromosome and remove empty chains\n",
    "    chrom = [list(chain) for chain in chrom if chain]\n",
    "    if not chrom:\n",
    "        return chrom\n",
    "\n",
    "    # Flatten all service trips\n",
    "    all_trips = [int(t) for chain in chrom for t in chain]\n",
    "    if not all_trips:\n",
    "        return chrom\n",
    "\n",
    "    # -------------------------\n",
    "    # Ruin phase\n",
    "    # -------------------------\n",
    "    # Select a fraction of service trips for removal\n",
    "    num_removed = max(1, round(len(all_trips) * float(ruin_frac)))\n",
    "    num_removed = min(num_removed, len(all_trips))\n",
    "\n",
    "    removed = set(rng.sample(all_trips, num_removed))\n",
    "\n",
    "    # Remove selected trips from all chains\n",
    "    partial_chains = [\n",
    "        [t for t in chain if t not in removed]\n",
    "        for chain in chrom\n",
    "    ]\n",
    "\n",
    "    # Keep only non-empty partial chains\n",
    "    partial_chains = [chain for chain in partial_chains if chain]\n",
    "\n",
    "    # -------------------------\n",
    "    # Helper functions\n",
    "    # -------------------------\n",
    "    def feasible(u: Optional[int], v: int) -> bool:\n",
    "        return _time_feasible_dt(\n",
    "            tt_best, dt_best, trips, u, v, allow_equal\n",
    "        )\n",
    "\n",
    "    def deadhead_cost(u: Optional[int], v: int) -> float:\n",
    "        \"\"\"\n",
    "        Deadhead cost from trip u to trip v.\n",
    "        If u is None, v is the first trip in a chain, so no previous\n",
    "        deadhead connection is counted.\n",
    "        \"\"\"\n",
    "        if not feasible(u, v):\n",
    "            return float(\"inf\")\n",
    "        return 0.0 if u is None else _tt_len(tt_best, int(u), int(v))\n",
    "\n",
    "    def insertion_delta(chain: List[int], pos: int, trip: int) -> float:\n",
    "        \"\"\"\n",
    "        Compute the incremental change in deadhead cost caused by inserting\n",
    "        trip at position pos in chain.\n",
    "        \"\"\"\n",
    "        u = None if pos == 0 else chain[pos - 1]\n",
    "        v = None if pos == len(chain) else chain[pos]\n",
    "\n",
    "        # Check feasibility with predecessor\n",
    "        if not feasible(u, trip):\n",
    "            return float(\"inf\")\n",
    "\n",
    "        # Check feasibility with successor\n",
    "        if v is not None and not feasible(trip, v):\n",
    "            return float(\"inf\")\n",
    "\n",
    "        # Insert at the end of a chain\n",
    "        if v is None:\n",
    "            return deadhead_cost(u, trip)\n",
    "\n",
    "        # Insert at the beginning of a chain\n",
    "        if u is None:\n",
    "            return (\n",
    "                deadhead_cost(None, trip)\n",
    "                + deadhead_cost(trip, v)\n",
    "                - deadhead_cost(None, v)\n",
    "            )\n",
    "\n",
    "        # Insert between two existing trips\n",
    "        return (\n",
    "            deadhead_cost(u, trip)\n",
    "            + deadhead_cost(trip, v)\n",
    "            - deadhead_cost(u, v)\n",
    "        )\n",
    "\n",
    "    # -------------------------\n",
    "    # Recreate phase\n",
    "    # -------------------------\n",
    "    # Reinsert removed trips one by one\n",
    "    for trip in removed:\n",
    "        best_delta = float(\"inf\")\n",
    "        best_chain_idx = None\n",
    "        best_pos = None\n",
    "\n",
    "        # Consider all insertion positions across current chains\n",
    "        for chain_idx, chain in enumerate(partial_chains):\n",
    "            for pos in range(len(chain) + 1):\n",
    "                delta = insertion_delta(chain, pos, trip)\n",
    "\n",
    "                if delta < best_delta:\n",
    "                    best_delta = delta\n",
    "                    best_chain_idx = chain_idx\n",
    "                    best_pos = pos\n",
    "\n",
    "        # Insert at the best feasible position\n",
    "        if best_chain_idx is not None and math.isfinite(best_delta):\n",
    "            partial_chains[best_chain_idx].insert(best_pos, trip)\n",
    "        else:\n",
    "            # If no feasible insertion exists in the current chains,\n",
    "            # create a new chain for this trip.\n",
    "            partial_chains.append([trip])\n",
    "\n",
    "    return [chain for chain in partial_chains if chain]"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
