{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64eea81d-ba10-4285-b87f-bdecc0f6169c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "from typing import Dict, List, Tuple\n",
    "from .types import Block, EnergyConfig, MergeCandidate\n",
    "\n",
    "\n",
    "def ceil_minutes(seconds: int) -> int:\n",
    "    return int(math.ceil(seconds / 60.0))\n",
    "\n",
    "\n",
    "def minutes_needed(energy_wh: float, charge_rate_wh_per_hour: float) -> int:\n",
    "    if energy_wh <= 0:\n",
    "        return 0\n",
    "\n",
    "    wh_per_minute = charge_rate_wh_per_hour / 60.0\n",
    "    return int(math.ceil(energy_wh / wh_per_minute))\n",
    "\n",
    "\n",
    "def block_start_time(block: Block, trips: Dict[int, dict]) -> int:\n",
    "    return int(trips[block[0]][\"start\"])\n",
    "\n",
    "\n",
    "def block_end_time(block: Block, trips: Dict[int, dict]) -> int:\n",
    "    return int(trips[block[-1]][\"end\"])\n",
    "\n",
    "\n",
    "def arc_duration(arc_dict: dict, key, default: int = 0) -> int:\n",
    "    arc = arc_dict.get(key)\n",
    "    if arc is None:\n",
    "        return default\n",
    "\n",
    "    data = arc[-1]\n",
    "    return int(data.get(\"duration\", 0))\n",
    "\n",
    "\n",
    "def arc_energy(arc_dict: dict, key, default: float = float(\"inf\")) -> float:\n",
    "    arc = arc_dict.get(key)\n",
    "    if arc is None:\n",
    "        return default\n",
    "\n",
    "    data = arc[-1]\n",
    "    return float(data.get(\"energy\", 0.0))\n",
    "\n",
    "\n",
    "def estimate_block_energy_need(\n",
    "    block: Block,\n",
    "    trips: Dict[int, dict],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    d5_best: Dict[int, tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Estimate the energy required to start this block from the depot,\n",
    "    serve all its trips, and finally return to the depot.\n",
    "    \"\"\"\n",
    "\n",
    "    head = block[0]\n",
    "    tail = block[-1]\n",
    "\n",
    "    total = arc_energy(d5_best, head)\n",
    "    total += float(trips[head].get(\"energy\", 0.0))\n",
    "\n",
    "    for u, v in zip(block, block[1:]):\n",
    "        total += arc_energy(tt_best, (u, v))\n",
    "        total += float(trips[v].get(\"energy\", 0.0))\n",
    "\n",
    "    total += arc_energy(td_best, tail)\n",
    "    total += config.min_soc_reserve\n",
    "\n",
    "    return total\n",
    "\n",
    "\n",
    "def build_block_merge_graph(\n",
    "    blocks: List[Block],\n",
    "    trips: Dict[int, dict],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    d5_best: Dict[int, tuple],\n",
    "    d6_best: Dict[int, tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> Tuple[Dict[int, List[int]], Dict[Tuple[int, int], MergeCandidate]]:\n",
    "    \"\"\"\n",
    "    Build feasible block-to-block connections.\n",
    "\n",
    "    A connection i -> j means:\n",
    "        block i -> depot -> charge -> depot -> block j\n",
    "\n",
    "    This is a simplified public version of the full duty-construction logic.\n",
    "    \"\"\"\n",
    "\n",
    "    adjacency: Dict[int, List[int]] = {i: [] for i in range(len(blocks))}\n",
    "    merge_info: Dict[Tuple[int, int], MergeCandidate] = {}\n",
    "\n",
    "    for i, first_block in enumerate(blocks):\n",
    "        tail_i = first_block[-1]\n",
    "\n",
    "        if tail_i not in d6_best:\n",
    "            continue\n",
    "\n",
    "        depot_i, _, d6_data = d6_best[tail_i]\n",
    "        arrive_depot = block_end_time(first_block, trips) + int(d6_data.get(\"duration\", 0))\n",
    "\n",
    "        for j, second_block in enumerate(blocks):\n",
    "            if i == j:\n",
    "                continue\n",
    "\n",
    "            head_j = second_block[0]\n",
    "\n",
    "            if head_j not in d5_best:\n",
    "                continue\n",
    "\n",
    "            depot_j, _, d5_data = d5_best[head_j]\n",
    "\n",
    "            if depot_i != depot_j:\n",
    "                continue\n",
    "\n",
    "            latest_depart = block_start_time(second_block, trips) - int(d5_data.get(\"duration\", 0))\n",
    "\n",
    "            if config.allow_equal_time:\n",
    "                if arrive_depot > latest_depart:\n",
    "                    continue\n",
    "            else:\n",
    "                if arrive_depot >= latest_depart:\n",
    "                    continue\n",
    "\n",
    "            available_minutes = max(0, (latest_depart - arrive_depot) // 60)\n",
    "\n",
    "            required_energy = estimate_block_energy_need(\n",
    "                block=second_block,\n",
    "                trips=trips,\n",
    "                tt_best=tt_best,\n",
    "                d5_best=d5_best,\n",
    "                td_best=td_best,\n",
    "                config=config,\n",
    "            )\n",
    "\n",
    "            required_charge_minutes = minutes_needed(\n",
    "                energy_wh=required_energy,\n",
    "                charge_rate_wh_per_hour=config.charge_rate_wh_per_hour,\n",
    "            )\n",
    "\n",
    "            if required_charge_minutes <= available_minutes:\n",
    "                adjacency[i].append(j)\n",
    "                merge_info[(i, j)] = MergeCandidate(\n",
    "                    from_block=i,\n",
    "                    to_block=j,\n",
    "                    arrive_depot_time=arrive_depot,\n",
    "                    latest_depart_time=latest_depart,\n",
    "                    required_charge_minutes=required_charge_minutes,\n",
    "                    depot_id=int(depot_i),\n",
    "                )\n",
    "\n",
    "    return adjacency, merge_info"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
