{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9ab68bf-8228-47a6-b7b6-998d5cbc2fb2",
   "metadata": {},
   "outputs": [],
   "source": [
    "from collections import deque\n",
    "from typing import Dict, List, Optional\n",
    "\n",
    "\n",
    "def hopcroft_karp(\n",
    "    left_nodes: List[int],\n",
    "    right_nodes: List[int],\n",
    "    adjacency: Dict[int, List[int]],\n",
    "):\n",
    "    \"\"\"\n",
    "    Maximum bipartite matching using Hopcroft-Karp.\n",
    "\n",
    "    Used to select a maximum set of non-conflicting block merges.\n",
    "    \"\"\"\n",
    "\n",
    "    pair_left = {u: None for u in left_nodes}\n",
    "    pair_right = {v: None for v in right_nodes}\n",
    "    dist = {}\n",
    "\n",
    "    def bfs() -> bool:\n",
    "        queue = deque()\n",
    "        found_path = False\n",
    "\n",
    "        for u in left_nodes:\n",
    "            if pair_left[u] is None:\n",
    "                dist[u] = 0\n",
    "                queue.append(u)\n",
    "            else:\n",
    "                dist[u] = float(\"inf\")\n",
    "\n",
    "        while queue:\n",
    "            u = queue.popleft()\n",
    "\n",
    "            for v in adjacency.get(u, []):\n",
    "                matched_u = pair_right[v]\n",
    "\n",
    "                if matched_u is None:\n",
    "                    found_path = True\n",
    "                elif dist[matched_u] == float(\"inf\"):\n",
    "                    dist[matched_u] = dist[u] + 1\n",
    "                    queue.append(matched_u)\n",
    "\n",
    "        return found_path\n",
    "\n",
    "    def dfs(u: int) -> bool:\n",
    "        for v in adjacency.get(u, []):\n",
    "            matched_u = pair_right[v]\n",
    "\n",
    "            if matched_u is None or (\n",
    "                dist[matched_u] == dist[u] + 1 and dfs(matched_u)\n",
    "            ):\n",
    "                pair_left[u] = v\n",
    "                pair_right[v] = u\n",
    "                return True\n",
    "\n",
    "        dist[u] = float(\"inf\")\n",
    "        return False\n",
    "\n",
    "    while bfs():\n",
    "        for u in left_nodes:\n",
    "            if pair_left[u] is None:\n",
    "                dfs(u)\n",
    "\n",
    "    return pair_left, pair_right\n",
    "\n",
    "\n",
    "def stitch_blocks_by_matching(\n",
    "    adjacency: Dict[int, List[int]],\n",
    "    number_of_blocks: int,\n",
    ") -> List[List[int]]:\n",
    "    \"\"\"\n",
    "    Convert selected block merges into duties.\n",
    "\n",
    "    Each duty is represented as a sequence of block indices.\n",
    "    \"\"\"\n",
    "\n",
    "    nodes = list(range(number_of_blocks))\n",
    "    pair_left, _ = hopcroft_karp(nodes, nodes, adjacency)\n",
    "\n",
    "    successor = {\n",
    "        u: v\n",
    "        for u, v in pair_left.items()\n",
    "        if v is not None\n",
    "    }\n",
    "\n",
    "    predecessor = {\n",
    "        v: u\n",
    "        for u, v in successor.items()\n",
    "    }\n",
    "\n",
    "    heads = [\n",
    "        node\n",
    "        for node in nodes\n",
    "        if node not in predecessor\n",
    "    ]\n",
    "\n",
    "    duties: List[List[int]] = []\n",
    "\n",
    "    for head in heads:\n",
    "        duty = [head]\n",
    "        current = head\n",
    "\n",
    "        while current in successor:\n",
    "            current = successor[current]\n",
    "            duty.append(current)\n",
    "\n",
    "        duties.append(duty)\n",
    "\n",
    "    covered = {block for duty in duties for block in duty}\n",
    "\n",
    "    for node in nodes:\n",
    "        if node not in covered:\n",
    "            duties.append([node])\n",
    "\n",
    "    return duties"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
