{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "64eea81d-ba10-4285-b87f-bdecc0f6169c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import math\n",
    "from typing import Dict, List, Tuple\n",
    "from .types import Block, EnergyConfig, MergeCandidate\n",
    "\n",
    "\n",
    "def ceil_minutes(seconds: int) -> int:\n",
    "    return int(math.ceil(seconds / 60.0))\n",
    "\n",
    "\n",
    "def minutes_needed(energy_wh: float, charge_rate_wh_per_hour: float) -> int:\n",
    "    if energy_wh <= 0:\n",
    "        return 0\n",
    "\n",
    "    wh_per_minute = charge_rate_wh_per_hour / 60.0\n",
    "    return int(math.ceil(energy_wh / wh_per_minute))\n",
    "\n",
    "\n",
    "def block_start_time(block: Block, trips: Dict[int, dict]) -> int:\n",
    "    return int(trips[block[0]][\"start\"])\n",
    "\n",
    "\n",
    "def block_end_time(block: Block, trips: Dict[int, dict]) -> int:\n",
    "    return int(trips[block[-1]][\"end\"])\n",
    "\n",
    "\n",
    "def arc_duration(arc_dict: dict, key, default: int = 0) -> int:\n",
    "    arc = arc_dict.get(key)\n",
    "    if arc is None:\n",
    "        return default\n",
    "\n",
    "    data = arc[-1]\n",
    "    return int(data.get(\"duration\", 0))\n",
    "\n",
    "\n",
    "def arc_energy(arc_dict: dict, key, default: float = float(\"inf\")) -> float:\n",
    "    arc = arc_dict.get(key)\n",
    "    if arc is None:\n",
    "        return default\n",
    "\n",
    "    data = arc[-1]\n",
    "    return float(data.get(\"energy\", 0.0))\n",
    "\n",
    "\n",
    "def estimate_block_energy_need(\n",
    "    block: Block,\n",
    "    trips: Dict[int, dict],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    d5_best: Dict[int, tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Energy required to leave the depot, serve the complete block,\n",
    "    return to the depot, and still satisfy the minimum SoC reserve.\n",
    "    \"\"\"\n",
    "\n",
    "    head = block[0]\n",
    "    tail = block[-1]\n",
    "\n",
    "    total = arc_energy(d5_best, head)\n",
    "    total += float(trips[head].get(\"energy\", 0.0))\n",
    "\n",
    "    for u, v in zip(block, block[1:]):\n",
    "        total += arc_energy(tt_best, (u, v))\n",
    "        total += float(trips[v].get(\"energy\", 0.0))\n",
    "\n",
    "    total += arc_energy(td_best, tail)\n",
    "    total += config.min_soc_reserve\n",
    "\n",
    "    return total\n",
    "\n",
    "\n",
    "def estimate_energy_after_block_return(\n",
    "    block: Block,\n",
    "    trips: Dict[int, dict],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    d5_best: Dict[int, tuple],\n",
    "    d6_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> float:\n",
    "    \"\"\"\n",
    "    Estimate the remaining battery energy after starting from the depot,\n",
    "    serving this block, and returning to the depot.\n",
    "\n",
    "    This is the arrival SoC at the depot after block i, used before deciding\n",
    "    how much charging is needed before starting block j.\n",
    "    \"\"\"\n",
    "\n",
    "    head = block[0]\n",
    "    tail = block[-1]\n",
    "\n",
    "    energy = config.battery_capacity\n",
    "\n",
    "    energy -= arc_energy(d5_best, head)\n",
    "    energy -= float(trips[head].get(\"energy\", 0.0))\n",
    "\n",
    "    for u, v in zip(block, block[1:]):\n",
    "        energy -= arc_energy(tt_best, (u, v))\n",
    "        energy -= float(trips[v].get(\"energy\", 0.0))\n",
    "\n",
    "    energy -= arc_energy(d6_best, tail)\n",
    "\n",
    "    return energy\n",
    "\n",
    "\n",
    "def build_block_merge_graph(\n",
    "    blocks: List[Block],\n",
    "    trips: Dict[int, dict],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    d5_best: Dict[int, tuple],\n",
    "    d6_best: Dict[int, tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> Tuple[Dict[int, List[int]], Dict[Tuple[int, int], MergeCandidate]]:\n",
    "    \"\"\"\n",
    "    Build feasible block-to-block connections.\n",
    "\n",
    "    A connection i -> j means:\n",
    "        block i -> depot -> charge if needed -> depot -> block j\n",
    "\n",
    "    This follows:\n",
    "        1. block i must be able to return to the depot,\n",
    "        2. block j must start from the same depot,\n",
    "        3. the dwell time between both blocks must be sufficient,\n",
    "        4. the required charging time must fit into the available dwell.\n",
    "    \"\"\"\n",
    "\n",
    "    adjacency: Dict[int, List[int]] = {i: [] for i in range(len(blocks))}\n",
    "    merge_info: Dict[Tuple[int, int], MergeCandidate] = {}\n",
    "\n",
    "    for i, first_block in enumerate(blocks):\n",
    "        tail_i = first_block[-1]\n",
    "\n",
    "        if tail_i not in d6_best:\n",
    "            continue\n",
    "\n",
    "        depot_i, _, d6_data = d6_best[tail_i]\n",
    "        return_to_depot_duration = int(d6_data.get(\"duration\", 0))\n",
    "        arrive_depot = block_end_time(first_block, trips) + return_to_depot_duration\n",
    "\n",
    "        energy_after_return = estimate_energy_after_block_return(\n",
    "            block=first_block,\n",
    "            trips=trips,\n",
    "            tt_best=tt_best,\n",
    "            d5_best=d5_best,\n",
    "            d6_best=d6_best,\n",
    "            config=config,\n",
    "        )\n",
    "\n",
    "        # Block i is not valid for merging if it cannot return with reserve.\n",
    "        if energy_after_return < config.min_soc_reserve:\n",
    "            continue\n",
    "\n",
    "        for j, second_block in enumerate(blocks):\n",
    "            if i == j:\n",
    "                continue\n",
    "\n",
    "            head_j = second_block[0]\n",
    "\n",
    "            if head_j not in d5_best:\n",
    "                continue\n",
    "\n",
    "            depot_j, _, d5_data = d5_best[head_j]\n",
    "\n",
    "            # Blocks can only be merged through the same depot.\n",
    "            if depot_i != depot_j:\n",
    "                continue\n",
    "\n",
    "            pull_out_duration = int(d5_data.get(\"duration\", 0))\n",
    "            latest_depart = block_start_time(second_block, trips) - pull_out_duration\n",
    "\n",
    "            if config.allow_equal_time:\n",
    "                if arrive_depot > latest_depart:\n",
    "                    continue\n",
    "            else:\n",
    "                if arrive_depot >= latest_depart:\n",
    "                    continue\n",
    "\n",
    "            available_seconds = latest_depart - arrive_depot\n",
    "            available_minutes = max(0, available_seconds // 60)\n",
    "\n",
    "            energy_needed_for_second_block = estimate_block_energy_need(\n",
    "                block=second_block,\n",
    "                trips=trips,\n",
    "                tt_best=tt_best,\n",
    "                d5_best=d5_best,\n",
    "                td_best=td_best,\n",
    "                config=config,\n",
    "            )\n",
    "\n",
    "            # If block j cannot be operated even from a full battery, skip it.\n",
    "            if energy_needed_for_second_block > config.battery_capacity:\n",
    "                continue\n",
    "\n",
    "            # Charge only the missing energy, not the whole energy requirement\n",
    "            # of the second block.\n",
    "            required_charge_energy = max(\n",
    "                0.0,\n",
    "                energy_needed_for_second_block - energy_after_return,\n",
    "            )\n",
    "\n",
    "            # Do not charge above battery capacity.\n",
    "            max_charge_possible = max(\n",
    "                0.0,\n",
    "                config.battery_capacity - energy_after_return,\n",
    "            )\n",
    "\n",
    "            if required_charge_energy > max_charge_possible:\n",
    "                continue\n",
    "\n",
    "            required_charge_minutes = minutes_needed(\n",
    "                energy_wh=required_charge_energy,\n",
    "                charge_rate_wh_per_hour=config.charge_rate_wh_per_hour,\n",
    "            )\n",
    "\n",
    "            if required_charge_minutes <= available_minutes:\n",
    "                adjacency[i].append(j)\n",
    "                merge_info[(i, j)] = MergeCandidate(\n",
    "                    from_block=i,\n",
    "                    to_block=j,\n",
    "                    arrive_depot_time=arrive_depot,\n",
    "                    latest_depart_time=latest_depart,\n",
    "                    required_charge_minutes=required_charge_minutes,\n",
    "                    depot_id=int(depot_i),\n",
    "                )\n",
    "\n",
    "    return adjacency, merge_info"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
