{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49e563e5-b6f5-499b-a9e7-4e4e3420891b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Dict, List, Tuple\n",
    "from .types import Chain, Block, EnergyConfig, DwellEvent\n",
    "from .energy_blocks import split_all_chains_into_blocks\n",
    "from .merge_graph import build_block_merge_graph\n",
    "from .matching import stitch_blocks_by_matching\n",
    "from .charging import schedule_charging_dwells\n",
    "\n",
    "\n",
    "def construct_duties_from_chains(\n",
    "    chains: List[Chain],\n",
    "    trips: Dict[int, dict],\n",
    "    dt_best: Dict[int, tuple],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    d5_best: Dict[int, tuple],\n",
    "    d6_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    "):\n",
    "    \"\"\"\n",
    "    Main duty-construction pipeline.\n",
    "\n",
    "    Input:\n",
    "        Time-feasible chains from the genetic algorithm.\n",
    "\n",
    "    Output:\n",
    "        Energy-aware duties, energy-feasible blocks, and scheduled depot dwells.\n",
    "    \"\"\"\n",
    "\n",
    "    blocks: List[Block] = split_all_chains_into_blocks(\n",
    "        chains=chains,\n",
    "        trips=trips,\n",
    "        dt_best=dt_best,\n",
    "        tt_best=tt_best,\n",
    "        td_best=td_best,\n",
    "        config=config,\n",
    "    )\n",
    "\n",
    "    adjacency, merge_info = build_block_merge_graph(\n",
    "        blocks=blocks,\n",
    "        trips=trips,\n",
    "        tt_best=tt_best,\n",
    "        d5_best=d5_best,\n",
    "        d6_best=d6_best,\n",
    "        td_best=td_best,\n",
    "        config=config,\n",
    "    )\n",
    "\n",
    "    duties = stitch_blocks_by_matching(\n",
    "        adjacency=adjacency,\n",
    "        number_of_blocks=len(blocks),\n",
    "    )\n",
    "\n",
    "    dwell_events: List[DwellEvent] = schedule_charging_dwells(\n",
    "        duties=duties,\n",
    "        merge_info=merge_info,\n",
    "        config=config,\n",
    "    )\n",
    "\n",
    "    return {\n",
    "        \"blocks\": blocks,\n",
    "        \"duties\": duties,\n",
    "        \"dwell_events\": dwell_events,\n",
    "        \"merge_graph\": adjacency,\n",
    "    }"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
