{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "45b56662-3d66-4039-bd26-6458991665b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "from typing import Dict, List, Tuple\n",
    "from .types import Chain, Block, EnergyConfig\n",
    "\n",
    "\n",
    "def trip_energy(trips: Dict[int, dict], trip_id: int) -> float:\n",
    "    return float(trips[trip_id].get(\"energy\", 0.0))\n",
    "\n",
    "\n",
    "def deadhead_energy(arc_dict: dict, key, default: float = float(\"inf\")) -> float:\n",
    "    arc = arc_dict.get(key)\n",
    "    if arc is None:\n",
    "        return default\n",
    "\n",
    "    # Supports both formats:\n",
    "    # tt_best[(u, v)] = (dh_id, data)\n",
    "    # dt_best[t] = (depot_id, dh_id, data)\n",
    "    data = arc[-1]\n",
    "    return float(data.get(\"energy\", 0.0))\n",
    "\n",
    "\n",
    "def can_return_to_depot(\n",
    "    trip_id: int,\n",
    "    remaining_energy: float,\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> bool:\n",
    "    if trip_id not in td_best:\n",
    "        return False\n",
    "\n",
    "    return_energy = deadhead_energy(td_best, trip_id)\n",
    "    return remaining_energy - return_energy >= config.min_soc_reserve\n",
    "\n",
    "\n",
    "def split_chain_into_energy_blocks(\n",
    "    chain: Chain,\n",
    "    trips: Dict[int, dict],\n",
    "    dt_best: Dict[int, tuple],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> List[Block]:\n",
    "    \"\"\"\n",
    "    Split a time-feasible trip chain into energy-feasible blocks.\n",
    "\n",
    "    A block starts from the depot, serves one or more trips, and must be able\n",
    "    to return to the depot with a safety reserve.\n",
    "    \"\"\"\n",
    "\n",
    "    blocks: List[Block] = []\n",
    "    i = 0\n",
    "\n",
    "    while i < len(chain):\n",
    "        energy = config.battery_capacity\n",
    "        current_block: Block = []\n",
    "        last_feasible_end = None\n",
    "\n",
    "        for j in range(i, len(chain)):\n",
    "            trip = chain[j]\n",
    "\n",
    "            if j == i:\n",
    "                needed = deadhead_energy(dt_best, trip, default=0.0)\n",
    "                needed += trip_energy(trips, trip)\n",
    "            else:\n",
    "                prev = chain[j - 1]\n",
    "                needed = deadhead_energy(tt_best, (prev, trip))\n",
    "                needed += trip_energy(trips, trip)\n",
    "\n",
    "            if energy - needed < 0:\n",
    "                break\n",
    "\n",
    "            energy -= needed\n",
    "            current_block.append(trip)\n",
    "\n",
    "            if can_return_to_depot(trip, energy, td_best, config):\n",
    "                last_feasible_end = j\n",
    "\n",
    "        if last_feasible_end is None:\n",
    "            # Fallback: keep one trip as a block.\n",
    "            # In the full implementation, this case should be logged or repaired.\n",
    "            blocks.append([chain[i]])\n",
    "            i += 1\n",
    "        else:\n",
    "            blocks.append(chain[i:last_feasible_end + 1])\n",
    "            i = last_feasible_end + 1\n",
    "\n",
    "    return blocks\n",
    "\n",
    "\n",
    "def split_all_chains_into_blocks(\n",
    "    chains: List[Chain],\n",
    "    trips: Dict[int, dict],\n",
    "    dt_best: Dict[int, tuple],\n",
    "    tt_best: Dict[Tuple[int, int], tuple],\n",
    "    td_best: Dict[int, tuple],\n",
    "    config: EnergyConfig,\n",
    ") -> List[Block]:\n",
    "    blocks: List[Block] = []\n",
    "\n",
    "    for chain in chains:\n",
    "        blocks.extend(\n",
    "            split_chain_into_energy_blocks(\n",
    "                chain=chain,\n",
    "                trips=trips,\n",
    "                dt_best=dt_best,\n",
    "                tt_best=tt_best,\n",
    "                td_best=td_best,\n",
    "                config=config,\n",
    "            )\n",
    "        )\n",
    "\n",
    "    return blocks"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
